spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "726245470910-kdis2dc6jsq4o12sp9tj72r6s9gees56.apps.googleusercontent.com"
            client-secret: "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"
            scope: "profile,email"
logging:
  level:
    org.hibernate.SQL: info
    com.kkulkkeog: debug
    root: info
file:
  base-path: "./src/main/resources/upload/"