spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootpassword
    jdbc-url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
  sql:
    init:
      platform: mysql
      mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "726245470910-kdis2dc6jsq4o12sp9tj72r6s9gees56.apps.googleusercontent.com"
            client-secret: "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"
            scope: "profile,email"

logging:
  level:
    org.hibernate.SQL: info
    com.kkulkkeog: debug
    root: info
file:
  base-path: "./src/main/resources/upload/"