package com.kkulkkeog.order.v1.api;

public enum OrderState {
    CREATE,
    MENU_VALIDATION_SUCCESS,
    MENU_VALIDATION_FAIL,
    COUPON_VALIDATION_SUCCESS,
    COUPON_CALCULATE_SUCCESS,
    COUPON_VALIDATION_FAIL,
    PAYMENT_FAIL,
    CANCEL,
    ORDER_SUCCESS
}
